sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
script:
- ./build.sh

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - trngcomplete@gmail.com
      - Sebastian-Markgraf@t-online.de
    on_success: never
    on_failure: always
